version: '3.5'

services:

  mongo:
    build:
      context: ../resources/database
      dockerfile: Dockerfile
    container_name: ep-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - mongo
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    container_name: ep-mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongo
    networks:
      - mongo

networks:
  mongo:
    driver: bridge
